### ISSUE TITLE
auth rqlite

### ISSUE THREAD

**Issue by fastsecuredrive** [rqlite/rqlite-dotnet#9]
My setup with rqlite uses basic authentication. Is there support for it in rqlite-dotnet?

  -u, --user
      set basic auth credentials in form username:password

**Comment by otoolep** [comment]
I didn't write this client library, but there are other libraries available that might be better fit?

https://rqlite.io/docs/api/client-libraries/#c

**Comment by fastsecuredrive** [comment]
Thank you @otoolep

**Comment by arthrp** [comment]
This functionality is available now
